/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

/*
module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
    docs : [

    ]
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
};
*/


module.exports = {
  mySidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // 自动根据 `docs` 或 `versioned_docs/<version>` 目录的文件结构生成侧边栏分片
    },
  ],
  docs: [
    'Home',
    {
      type: 'category',
      label: '程序语言',
      items: [
          'C++',
      ],
    },
    {
      type: 'category',
      label: '程序设计',
      items: [
          '英文词标准缩写',
      ],
    },
    {
      type: 'category',
      label: 'Linux相关',
      items: [
          'Git',
      ],
    },

    {
      type: 'category',
      label: '技能',
      items: [
        //'我是如何做数据容灾的',
      ],
    },
    {
      type: 'category',
      label: '自然科学',
      items: [
        '具体数学',
      ],
    },

    {
      type: 'category',
      label: '认知',
      items: [
        //'思想',
      ],
    },

    {
      type: 'category',
      label: 'reading book',
      items: [
        //'LaTex',
      ],
    },

  ],
};

